// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk228017445/appengine/go_appengine/goroot-1.6`
const TheVersion = `1.6.4 (appengine-1.9.60)`
const Goexperiment = ``
const StackGuardMultiplier = 1

