// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk088345691/appengine/go_appengine/goroot-1.6`
const TheVersion = `1.6.3 (appengine-1.9.53)`
const Goexperiment = ``
const StackGuardMultiplier = 1

