// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk247347244/appengine/go_appengine/goroot-1.6`
const TheVersion = `1.6.4 (appengine-1.9.57)`
const Goexperiment = ``
const StackGuardMultiplier = 1

