// auto generated by go tool dist

package runtime

const defaultGoroot = `/private/var/folders/00/1_z98000h01000cxqpysvccm005bx5/T/appengine/go_appengine/goroot`
const theVersion = `go1.4.2 (appengine-1.9.34)`
var buildVersion = theVersion
