// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk994978379/appengine/go_appengine/goroot-1.8`
const TheVersion = `1.8.3 (appengine-1.9.56)`
const Goexperiment = ``
const StackGuardMultiplier = 1

