// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/appengine/go_appengine/goroot`
const TheVersion = `go1.6.1 (appengine-1.9.37)`
const Goexperiment = ``
const StackGuardMultiplier = 1

